name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.14"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"

    - name: Debug: List installed packages
      run: uv pip list

    - name: Debug: Show .pth files and content
      run: |
        find .venv -name "*.pth" -exec echo {} \; -exec cat {} \;

    # - name: Type check with mypy
    #   run: uv run mypy src/

    # - name: Lint code with Ruff
    #   run: uv run ruff check --output-format=github --target-version=py311

    - name: Check code formatting
      run: uv run ruff format --check --diff --target-version=py311

    - name: Test with pytest
      run: uv run pytest --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v4
      with:
        name: junit-results
        path: junit/test-results.xml

    - name: Update coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
